drop table if exists config;
create table config (
  `id` integer auto_increment,
  `timestamp` timestamp default 0,
  `ackTimestamp` timestamp default 0,
  `battery` varchar(32),
  `username` varchar(32),
  `manualTimeout` int,
  `pump0` boolean,
  `pump1` boolean,
  `pump2` boolean,
  `pump3` boolean,
  `targetFlow` int,
  `targetLevel1` int,
  `targetLevel2` int,
  `targetLevel3` int,
  `targetLevel4` int,
  `minLevel1` int,
  `minLevel2` int,
  `minLevel3` int,
  `minLevel4` int,
  `maxLevel1` int,
  `maxLevel2` int,
  `maxLevel3` int,
  `maxLevel4` int,
  primary key(id)
);

drop table if exists status;
create table status (
  `id` integer auto_increment,
  `timestamp` timestamp default 0,
  `battery` varchar(16),
  `panic` boolean,
  `manualTimeout` int,
  `pump0` int,
  `pump1` int,
  `pump2` int,
  `pump3` int,
  `targetFlow` int,
  `fwdFlowIn` int,
  `revFlowIn` int,
  `fwdFlowOut` int,
  `revFlowOut` int,
  `currentLevel1` int,
  `currentLevel2` int,
  `currentLevel3` int,
  `targetLevel1` int,
  `targetLevel2` int,
  `targetLevel3` int,
  `minLevel1` int,
  `minLevel2` int,
  `minLevel3` int,
  `maxLevel1` int,
  `maxLevel2` int,
  `maxLevel3` int,
  primary key(id)
);
